# Generated by Django 4.1.3 on 2022-12-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='activity_id',
        ),
    ]
