# Generated by Django 4.1.3 on 2022-12-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_post_activity_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author_id',
            new_name='author',
        ),
    ]
