# Generated by Django 4.1.3 on 2022-12-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_author_id_activity_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='post',
        ),
    ]
