# Generated by Django 4.1.3 on 2022-12-09 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_activity_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_category',
            field=models.CharField(choices=[('Swimming', 'Swimming'), ('Yoga', 'Yoga'), ('Running3', 'Running'), ('Snowboarding', 'Snowboarding'), ('Push-ups', 'Push-ups'), ('Walking', 'Walking'), ('Surfing', 'Surfing'), ('Diving', 'Diving'), ('Cycling', 'Cycling'), ('Climbing Stairs', 'Climbing Stairs')], default='available', max_length=32),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_name',
            field=models.CharField(max_length=50),
        ),
    ]
