# Generated by Django 4.1.3 on 2022-12-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_profile_profileimg_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
