# Generated by Django 4.1.3 on 2022-12-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_isprivate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='isPrivate',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
