# Generated by Django 4.1.3 on 2022-12-31 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_profile_isprivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
