# Generated by Django 4.1.3 on 2023-01-03 13:24

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_activity_activity_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvs/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_category',
            field=models.CharField(choices=[('Swimming', 'Swimming'), ('Yoga', 'Yoga'), ('Running', 'Running'), ('Snowboarding', 'Snowboarding'), ('Push-ups', 'Push-ups'), ('Walking', 'Walking'), ('Surfing', 'Surfing'), ('Diving', 'Diving'), ('Cycling', 'Cycling'), ('Climbing Stairs', 'Climbing Stairs')], default='available', max_length=32),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_duration',
            field=models.DurationField(default=datetime.timedelta, validators=[main.models.validate]),
        ),
    ]
