# Generated by Django 4.1.3 on 2023-01-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_mycsv_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selectMenu',
            field=models.BooleanField(default=False),
        ),
    ]
