# Generated by Django 4.1.3 on 2023-01-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_profile_selectmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selectMenu',
            field=models.CharField(choices=[('Bar chart', 'Bar chart'), ('Pie chart', 'Pie chart')], default='Bar chart', max_length=32),
        ),
    ]
