# Generated by Django 4.1.3 on 2023-01-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_profile_selectmenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='selectMenu',
        ),
    ]
